import type { StoreData } from "./types";

const now = Date.now();
const hours = (h: number) => new Date(now - h * 3600_000).toISOString();

export const SEED_DATA: StoreData = {
  categories: [
    {
      id: "cat-product",
      name: "Product ideas",
      description: "Feature requests and product improvements for the core product.",
      emoji: "💡",
      createdAt: hours(720),
      sortOrder: 0,
    },
    {
      id: "cat-ops",
      name: "Operations",
      description: "Process, tooling, and internal workflow suggestions.",
      emoji: "⚙️",
      createdAt: hours(700),
      sortOrder: 1,
    },
    {
      id: "cat-events",
      name: "Events & community",
      description: "Ideas for meetups, programs, and community initiatives.",
      emoji: "📅",
      createdAt: hours(680),
      sortOrder: 2,
    },
  ],
  tags: [
    { id: "tag-ui", categoryId: "cat-product", name: "UI", color: "#3BA55D" },
    { id: "tag-api", categoryId: "cat-product", name: "API", color: "#3498DB" },
    { id: "tag-perf", categoryId: "cat-product", name: "Performance", color: "#E67E22" },
    { id: "tag-a11y", categoryId: "cat-product", name: "Accessibility", color: "#9B59B6" },
    { id: "tag-process", categoryId: "cat-ops", name: "Process", color: "#1ABC9C" },
    { id: "tag-tooling", categoryId: "cat-ops", name: "Tooling", color: "#E74C3C" },
    { id: "tag-docs", categoryId: "cat-ops", name: "Docs", color: "#F1C40F" },
    { id: "tag-meetup", categoryId: "cat-events", name: "Meetup", color: "#2ECC71" },
    { id: "tag-program", categoryId: "cat-events", name: "Program", color: "#E91E63" },
  ],
  suggestions: [
    {
      id: "sug-1",
      categoryId: "cat-product",
      title: "Allow filtering suggestions by multiple tags at once",
      body: "Today you can only filter by one tag. Being able to combine tags (e.g. UI + Accessibility) would make triage much faster for admins reviewing large categories.",
      authorName: "Alex Chen",
      tagIds: ["tag-ui", "tag-a11y"],
      pinned: true,
      createdAt: hours(48),
      updatedAt: hours(2),
      replyCount: 3,
    },
    {
      id: "sug-2",
      categoryId: "cat-product",
      title: "Export category threads to CSV for quarterly reviews",
      body: "We do quarterly planning and currently copy threads by hand. A CSV export with title, tags, author, reply count, and last activity would save a lot of time.",
      authorName: "Jordan Lee",
      tagIds: ["tag-api"],
      pinned: false,
      createdAt: hours(36),
      updatedAt: hours(8),
      replyCount: 1,
    },
    {
      id: "sug-3",
      categoryId: "cat-product",
      title: "Keyboard shortcuts for pinning and tagging posts",
      body: "Power users spend a lot of time in the forum list. Shortcuts like `P` to pin and `T` to open the tag picker would speed up moderation.",
      authorName: "Sam Rivera",
      tagIds: ["tag-ui", "tag-perf"],
      pinned: false,
      createdAt: hours(20),
      updatedAt: hours(20),
      replyCount: 0,
    },
    {
      id: "sug-4",
      categoryId: "cat-ops",
      title: "Standardize onboarding checklist for new admins",
      body: "New category admins get inconsistent handoffs. A shared checklist (permissions, tag taxonomy, pinning guidelines) would reduce support load.",
      authorName: "Morgan Blake",
      tagIds: ["tag-process", "tag-docs"],
      pinned: true,
      createdAt: hours(60),
      updatedAt: hours(5),
      replyCount: 2,
    },
    {
      id: "sug-5",
      categoryId: "cat-ops",
      title: "Add Slack digest for new high-activity threads",
      body: "When a suggestion gets more than 5 replies in a day, post a short digest to #product-triage so owners notice without watching the board constantly.",
      authorName: "Casey Ng",
      tagIds: ["tag-tooling"],
      pinned: false,
      createdAt: hours(12),
      updatedAt: hours(3),
      replyCount: 1,
    },
    {
      id: "sug-6",
      categoryId: "cat-events",
      title: "Host a monthly office hours for top-voted ideas",
      body: "Pick 3 pinned or highly replied suggestions each month and run a 30-minute office hours so authors can talk through details with owners.",
      authorName: "Riley Patel",
      tagIds: ["tag-meetup", "tag-program"],
      pinned: false,
      createdAt: hours(28),
      updatedAt: hours(6),
      replyCount: 2,
    },
  ],
  replies: [
    {
      id: "rep-1",
      suggestionId: "sug-1",
      body: "Strong +1. We already store tag IDs as arrays — multi-select filters should be straightforward on the list view.",
      authorName: "Dana Okonkwo",
      createdAt: hours(40),
    },
    {
      id: "rep-2",
      suggestionId: "sug-1",
      body: "Please keep AND semantics for multi-tag filters so we can narrow, not broaden.",
      authorName: "Alex Chen",
      createdAt: hours(10),
    },
    {
      id: "rep-3",
      suggestionId: "sug-1",
      body: "Agreed on AND. Also show an active-filter chip row under the sort controls.",
      authorName: "Priya Shah",
      createdAt: hours(2),
    },
    {
      id: "rep-4",
      suggestionId: "sug-2",
      body: "We can start with a category-scoped export. Column set looks right.",
      authorName: "Dana Okonkwo",
      createdAt: hours(8),
    },
    {
      id: "rep-5",
      suggestionId: "sug-4",
      body: "I drafted a first version in Notion — happy to migrate it into the admin docs section.",
      authorName: "Taylor Brooks",
      createdAt: hours(30),
    },
    {
      id: "rep-6",
      suggestionId: "sug-4",
      body: "Let's include tag naming conventions and when to pin vs. leave unpinned.",
      authorName: "Morgan Blake",
      createdAt: hours(5),
    },
    {
      id: "rep-7",
      suggestionId: "sug-5",
      body: "Threshold of 5 feels right. Maybe also include newly pinned posts.",
      authorName: "Jordan Lee",
      createdAt: hours(3),
    },
    {
      id: "rep-8",
      suggestionId: "sug-6",
      body: "Love this. Could rotate hosts between product and ops so both sides show up.",
      authorName: "Sam Rivera",
      createdAt: hours(18),
    },
    {
      id: "rep-9",
      suggestionId: "sug-6",
      body: "Happy to pilot next month with the Product ideas category.",
      authorName: "Riley Patel",
      createdAt: hours(6),
    },
  ],
};
